# Generated by Django 5.1.7 on 2025-03-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dira_app', '0002_remove_agrovet_profile_remove_farmer_profile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
