# Generated by Django 5.1.7 on 2025-03-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dira_app', '0004_diagnosis_resource_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrovet',
            name='agrovet_location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farm_location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
